#ifndef WTQ_PROTO_QPACK_STATIC_H
#define WTQ_PROTO_QPACK_STATIC_H

/*
 * Static-only QPACK field-section codec (RFC 9204, static table from
 * Appendix A; Huffman code from RFC 7541 Appendix B, decode-only).
 *
 * INTERNAL header — not installed, never included from public headers.
 *
 * Scope (wtquic v1, by contract):
 *   - No dynamic table: the field-section prefix MUST be {0x00, 0x00}
 *     (Required Insert Count 0, sign clear, Delta Base 0); any dynamic
 *     or post-base field line form is MALFORMED.
 *   - Decoder handles plain and Huffman string literals; the encoder
 *     emits plain literals only and prefers, per field:
 *       exact static name+value  -> Indexed Field Line (static)
 *       static name only         -> Literal With Name Reference (static)
 *       otherwise                -> Literal With Literal Name
 *   - Decode consumes the EXACT field-section span (the caller hands us
 *     one complete HEADERS payload): bytes left over or missing are
 *     MALFORMED, not NEED_MORE.
 *   - No allocation: decoded literal strings are copied into caller
 *     scratch; static-table references point into the static table.
 *     Every returned span lies in exactly one of those two places.
 *   - Duplicate headers and HTTP semantics are the connect layer's job;
 *     this module only preserves ordered fields.
 *
 * Static and Huffman tables are generated by scripts/gen_qpack_tables.py
 * from Google QUICHE's and picoquic h3zero's tables (cross-checked);
 * see src/proto/qpack_tables.inc for provenance.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define WTQ_QPACK_STATIC_COUNT 99u

typedef int wtq_qpack_status_t;
#define WTQ_QPACK_OK        0
#define WTQ_QPACK_NEED_MORE 1  /* prefixed-int helpers only */
#define WTQ_QPACK_BUFFER    (-1) /* dst/fields/scratch too small */
#define WTQ_QPACK_RANGE     (-2) /* encode value out of range */
#define WTQ_QPACK_MALFORMED (-3) /* dynamic/post-base reference, bad
                                    prefix, bad Huffman, bad integer,
                                    span under/overrun */

/* --- QPACK prefixed integers (RFC 7541 s5.1 / RFC 9204 s4.1.1) ------- */
/*
 * prefix_bits in [3, 8]. Encode writes the prefix byte as
 * (first_byte_flags | encoded-prefix); flags must not intersect the
 * prefix mask. Decode reads flag bits implicitly (caller inspects
 * src[0] itself) and returns the integer value.
 * Values are capped at 2^62-1: larger decodes are MALFORMED, larger
 * encodes RANGE. Decode returns NEED_MORE on truncation.
 */
wtq_qpack_status_t wtq_qpack_int_encode(uint64_t value,
                                        uint8_t first_byte_flags,
                                        unsigned prefix_bits, uint8_t *dst,
                                        size_t cap, size_t *out_len);
wtq_qpack_status_t wtq_qpack_int_decode(const uint8_t *src, size_t len,
                                        unsigned prefix_bits,
                                        uint64_t *value, size_t *consumed);

/* --- static table ----------------------------------------------------- */

/* Entry lookup by index [0, 98]. Returns false for out-of-range.
 * name/value point at static storage (never NULL; empty value = ""). */
bool wtq_qpack_static_get(uint64_t index, const char **name,
                          size_t *name_len, const char **value,
                          size_t *value_len);

/* Exact name+value match -> index, or -1. Case-sensitive byte match
 * (header names in the table are lowercase; callers normalize). */
int wtq_qpack_static_find(const char *name, size_t name_len,
                          const char *value, size_t value_len);

/* First static entry with this name -> index, or -1. */
int wtq_qpack_static_find_name(const char *name, size_t name_len);

/* --- fields ------------------------------------------------------------ */

typedef struct wtq_qpack_field {
    const char *name;  /* into static table or caller scratch */
    size_t name_len;
    const char *value; /* into static table or caller scratch */
    size_t value_len;
    bool never_index;  /* the N bit, surfaced for completeness */
} wtq_qpack_field_t;

/* --- field-section decode ---------------------------------------------- */
/*
 * Decode one complete encoded field section (prefix + field lines).
 * Fields are appended to fields[] in wire order; literal strings are
 * copied (Huffman-decoded where marked) into scratch back-to-back.
 * BUFFER when max_fields or scratch_cap is insufficient. MALFORMED for
 * any dynamic-table dependence, invalid prefix, invalid Huffman
 * (EOS symbol, bad padding, > 7 padding bits), integer overflow, or a
 * span under/overrun.
 */
wtq_qpack_status_t wtq_qpack_decode_section(const uint8_t *src, size_t len,
                                            wtq_qpack_field_t *fields,
                                            size_t max_fields,
                                            size_t *out_count,
                                            char *scratch,
                                            size_t scratch_cap);

/* --- field-section encode ---------------------------------------------- */
/*
 * Encode fields (in order) as a static-only field section, prefix
 * included. Plain literals only (no Huffman). RANGE when a name/value
 * length exceeds what a prefixed int can carry (practically unreachable);
 * BUFFER when cap is too small. dst untouched on any error.
 */
wtq_qpack_status_t wtq_qpack_encode_section(const wtq_qpack_field_t *fields,
                                            size_t count, uint8_t *dst,
                                            size_t cap, size_t *out_len);

#ifdef __cplusplus
}
#endif

#endif /* WTQ_PROTO_QPACK_STATIC_H */
